#!/bin/bash
# This feels like a hack.  There should be a way of making the push automatic for all the tags
CONFLUENT_VERSION="5.5.1"

# tagged in the build
#docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$CONFLUENT_VERSION